# Generated by Django 2.2.5 on 2019-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='dispatch_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
